version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    container_name: mongo
  api:
    build: https://github.com/rd-dev-ukraine/campaigns-list-server.git
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    links:
      - mongodb

  client:
    build: https://github.com/rd-dev-ukraine/campaigns-list-client.git
    stdin_open: true
    tty: true
    depends_on: 
      - api
    ports:
      - 3000:5000