version: "3"
services:
  mongo-primary:
    image: mongo:4.1.13-bionic
    command: --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
  mongo-secondary:
    image: mongo:4.1.13-bionic
    command: --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    depends_on:
      - mongo-primary
  mongo-replicator:
    build: 
      context: ./
      dockerfile: ./mongo-replicator.Dockerfile
    depends_on:
      - mongo-primary
      - mongo-secondary
  api:
    build: https://github.com/rd-dev-ukraine/campaigns-list-server.git
    environment: 
      - PORT=4000
      - DB_URL=mongodb://mongo-primary:27017/campaigns?replicateSet=rs0
      - RS=rs0
    depends_on:
      - mongo-primary
      - mongo-secondary
    ports:
      - 4000:4000
    links:
      - mongo-primary
      - mongo-secondary
  client:
    build: 
      context: https://github.com/rd-dev-ukraine/campaigns-list-client.git
      args: 
        REACT_APP_API_URL: http://localhost:4000
    stdin_open: true
    tty: true
    depends_on: 
      - api
    ports:
      - 3000:5000