version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongo
  api:
    build: https://github.com/rd-dev-ukraine/campaigns-list-server.git
    environment: 
      - PORT=4000
      - DB_URL=mongodb://mongodb/campaigns
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    links:
      - mongodb

  client:
    build: 
      context: https://github.com/rd-dev-ukraine/campaigns-list-client.git
      args: 
        REACT_APP_API_URL: http://localhost:4000
    stdin_open: true
    tty: true
    depends_on: 
      - api
    ports:
      - 3000:5000